parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"DCTP":[function(require,module,exports) {
function r(r){if(Array.isArray(r))return r}module.exports=r;
},{}],"LoeL":[function(require,module,exports) {
function r(r,t){if("undefined"!=typeof Symbol&&Symbol.iterator in Object(r)){var e=[],n=!0,o=!1,l=void 0;try{for(var i,u=r[Symbol.iterator]();!(n=(i=u.next()).done)&&(e.push(i.value),!t||e.length!==t);n=!0);}catch(a){o=!0,l=a}finally{try{n||null==u.return||u.return()}finally{if(o)throw l}}return e}}module.exports=r;
},{}],"jEQo":[function(require,module,exports) {
function n(n,r){(null==r||r>n.length)&&(r=n.length);for(var e=0,l=new Array(r);e<r;e++)l[e]=n[e];return l}module.exports=n;
},{}],"Dbv9":[function(require,module,exports) {
var r=require("./arrayLikeToArray");function t(t,e){if(t){if("string"==typeof t)return r(t,e);var o=Object.prototype.toString.call(t).slice(8,-1);return"Object"===o&&t.constructor&&(o=t.constructor.name),"Map"===o||"Set"===o?Array.from(t):"Arguments"===o||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(o)?r(t,e):void 0}}module.exports=t;
},{"./arrayLikeToArray":"jEQo"}],"MWEO":[function(require,module,exports) {
function e(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}module.exports=e;
},{}],"DERy":[function(require,module,exports) {
var r=require("./arrayWithHoles"),e=require("./iterableToArrayLimit"),t=require("./unsupportedIterableToArray"),i=require("./nonIterableRest");function u(u,a){return r(u)||e(u,a)||t(u,a)||i()}module.exports=u;
},{"./arrayWithHoles":"DCTP","./iterableToArrayLimit":"LoeL","./unsupportedIterableToArray":"Dbv9","./nonIterableRest":"MWEO"}],"cQfh":[function(require,module,exports) {
function e(e,r,n){return r in e?Object.defineProperty(e,r,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[r]=n,e}module.exports=e;
},{}],"xOn8":[function(require,module,exports) {
function o(t){return"function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?module.exports=o=function(o){return typeof o}:module.exports=o=function(o){return o&&"function"==typeof Symbol&&o.constructor===Symbol&&o!==Symbol.prototype?"symbol":typeof o},o(t)}module.exports=o;
},{}],"l1PD":[function(require,module,exports) {
var global = arguments[3];
var e=arguments[3],t=l(require("@babel/runtime/helpers/slicedToArray")),n=l(require("@babel/runtime/helpers/defineProperty")),r=l(require("@babel/runtime/helpers/typeof"));function l(e){return e&&e.__esModule?e:{default:e}}!function(e,t,n){"undefined"!=typeof module&&"object"===("undefined"==typeof exports?"undefined":(0,r.default)(exports))?module.exports=n():t[e]=n()}("WPTB_ExtraStyles",self||e,function(){return new function(){var e,r=this;this.modes={builder:"builder",frontEnd:"frontEnd",block:"block"},this.baseDocument=document,this.currentMode=this.modes.builder,this.generalStyles="";var l=(e={},(0,n.default)(e,this.modes.builder,".wptb-table-setup .wptb-preview-table"),(0,n.default)(e,this.modes.block,".wptb-block-table-setup .wptb-preview-table"),(0,n.default)(e,this.modes.frontEnd,".wptb-table-container .wptb-preview-table"),e),o=function(e,t){var n=t.replaceAll(/(\r?\n)|(\/\*.+?\*\/)|(\s*!important)/g,"").replaceAll(";"," !important;").split("}"),r=[];return n.map(function(t){var n=new RegExp(/(.+?)\{/g).exec(t);n&&(e===n[1].trim()?r.push(t):r.push(t.replace(n[1],"".concat(e," ").concat(n[1]))))}),"".concat(r.join("}"),"}")},a=function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null,n=document.createElement("style");n.type="text/css",n.id="wptb-general-styles",t?t.insertAdjacentElement("beforebegin",n):(r.currentMode===r.modes.block?r.baseDocument:r.baseDocument.querySelector("head")).appendChild(n);var l=o(e.parentPrefix,e.styles);n.appendChild(document.createTextNode(l))},d=function(e){var n=e.dataset.wptbExtraStyles;if(n){var l=atob(n),d=e.getAttribute("class").match(/wptb-element-main-table_setting-(?:startedid-)?(\d+)/),s=(0,t.default)(d,2)[1],i="wptb-extra-styles-"+s,c=r.baseDocument.querySelector("head"),u=null==c?void 0:c.querySelector("#".concat(i));u||((u=document.createElement("style")).type="text/css",u.id=i,e.dataset.disableThemeStyles&&r.currentMode===r.modes.frontEnd||r.currentMode===r.modes.block?(e.insertAdjacentElement("beforebegin",u),r.currentMode===r.modes.frontEnd&&r.generalStyles&&a(r.generalStyles,e)):c.appendChild(u));var b=".wptb-element-main-table_setting-".concat(s),p=o(b,l);u.innerHTML="",u.appendChild(document.createTextNode(p))}};this.applyStyles=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:r.modes.frontEnd,t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null,n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:document;r.baseDocument=n,r.currentMode=e,r.generalStyles=t;var o=Array.from(r.baseDocument.querySelectorAll(l[e]));o&&o.map(d),e!==r.modes.frontEnd&&e!==r.modes.block||!t||a(t)}}});
},{"@babel/runtime/helpers/slicedToArray":"DERy","@babel/runtime/helpers/defineProperty":"cQfh","@babel/runtime/helpers/typeof":"xOn8"}],"fA4i":[function(require,module,exports) {
"use strict";var e=t(require("../WPTB_ExtraStyles"));function t(e){return e&&e.__esModule?e:{default:e}}var l=document.querySelector("#wptb-block-preview-base").shadowRoot;e.default.applyStyles(e.default.modes.block,null,l);
},{"../WPTB_ExtraStyles":"l1PD"}]},{},["fA4i"], null)